import type { Project, TimelineItem, Certification, SocialLink, Stat, HeroBadge } from '@/types'

export const PERSONAL_INFO = {
  name: 'Shankar Mattavelli',
  nameFirstLine: 'Shankar',
  nameSecondLine: 'Mattavelli',
  role: 'Frontend Developer',
  location: 'Milano, Italia',
  bio: 'Sono alla ricerca di opportunità nel settore IT con focus su 3D interattivo e visual computing.',
  email: 'shankar.mattavelli@gmail.com',
  phone: '+39 334 925 0900',
  linkedin: 'https://www.linkedin.com/in/shankar-mattavelli',
  objective: 'Ruolo IT / Developer con focus su Computer Graphics, WebGL e Interactive 3D',
} as const

export const STATS: Stat[] = [
  { value: '6+', label: 'PROGETTI' },
  { value: '6', label: 'CERTIFICAZIONI' },
  { value: '5+', label: 'ANNI' },
]

export const HERO_BADGES: HeroBadge[] = [
  { label: 'React', top: '11%', left: '0%', floatDelay: 0, floatDuration: 4.2 },
  { label: 'Three.js', top: '21%', left: '13%', floatDelay: 0.5, floatDuration: 3.8 },
  { label: 'Node.js', top: '9%', right: '20%', floatDelay: 1.2, floatDuration: 4.5 },
  { label: 'After Effects', top: '37%', right: '1%', floatDelay: 0.8, floatDuration: 3.6 },
  { label: 'Cinema 4D', top: '66%', right: '18%', floatDelay: 1.5, floatDuration: 4.1 },
  { label: 'Blender', top: '54%', left: '40%', floatDelay: 0.3, floatDuration: 3.9 },
  { label: 'WebGL', top: '75%', left: '54%', floatDelay: 1.0, floatDuration: 4.3 },
  { label: 'Python', top: '82%', right: '9%', floatDelay: 0.6, floatDuration: 4.0 },
]

export const PROJECTS: Project[] = [
  {
    id: 'strata',
    num: '01',
    title: 'Strata',
    category: 'DATA DASHBOARD',
    year: '2024',
    tags: ['3D'],
    techTags: ['React', 'Three.js', 'D3.js', 'WebGL'],
    slug: 'strata',
    description: 'Dashboard interattiva per la visualizzazione di dati complessi in tempo reale, con scene 3D integrate.',
    role: 'Solo Developer',
    duration: '2 mesi',
    type: 'Data Dashboard',
  },
  {
    id: 'nocturne',
    num: '02',
    title: 'Nocturne',
    category: 'INTERACTIVE EXPERIENCE',
    year: '2024',
    tags: ['3D'],
    techTags: ['Three.js', 'Web Audio API', 'GLSL', 'WebGL'],
    slug: 'nocturne',
    description: 'Piattaforma di visualizzazione musicale in tempo reale — le frequenze audio diventano forme geometriche animate.',
    role: 'Solo Developer & Creative Director',
    duration: '3 mesi',
    type: 'Interactive Experience',
  },
  {
    id: 'forma',
    num: '03',
    title: 'Forma',
    category: 'BRAND & MOTION',
    year: '2023',
    tags: [],
    techTags: ['Cinema 4D', 'After Effects', 'Branding', 'Motion'],
    slug: 'forma',
    description: 'Identità visiva e motion design per uno studio di architettura a Milano — logo, tipografia, animazioni.',
    role: 'Brand Designer & Motion Artist',
    duration: '2 mesi',
    type: 'Brand & Motion',
  },
  {
    id: 'reverie',
    num: '04',
    title: 'Reverie',
    category: '3D E-COMMERCE',
    year: '2023',
    tags: ['3D'],
    techTags: ['React', 'Three.js', 'GSAP', 'WebGL'],
    slug: 'reverie',
    description: 'Piattaforma e-commerce con configuratore 3D interattivo per prodotti di lusso.',
    role: 'Frontend Developer',
    duration: '4 mesi',
    type: '3D E-Commerce',
  },
  {
    id: 'atlas',
    num: '05',
    title: 'Atlas',
    category: 'INTERACTIVE MAP',
    year: '2023',
    tags: ['3D'],
    techTags: ['Three.js', 'D3.js', 'GeoJSON', 'WebGL'],
    slug: 'atlas',
    description: 'Mappa interattiva 3D per la visualizzazione geografica di dati climatici globali.',
    role: 'Frontend Developer',
    duration: '3 mesi',
    type: 'Interactive Map',
  },
  {
    id: 'prism',
    num: '06',
    title: 'Prism',
    category: 'CREATIVE TOOL',
    year: '2023',
    tags: [],
    techTags: ['Canvas API', 'WebGL', 'GLSL', 'Generative'],
    slug: 'prism',
    description: 'Tool creativo browser-based per la generazione procedurale di pattern visivi.',
    role: 'Solo Developer',
    duration: '1 mese',
    type: 'Creative Tool',
  },
]

export const TIMELINE: TimelineItem[] = [
  {
    id: 'decathlon',
    side: 'left',
    institution: 'DECATHLON',
    role: 'Magazziniere',
    year: '2020',
    yearRange: 'ott 2020 – giu 2021',
    location: 'Basiano (MI)',
    description: 'Contratto a chiamata. Gestione magazzino, ricezione e smistamento merci, picking e riassortimento scaffali in ambiente logistico ad alto volume.',
    logo: '/logos/decathlon.jpg',
  },
  {
    id: 'lambdacorp',
    side: 'right',
    institution: 'LAMBDACORP PROJECT TEAM',
    role: 'Unreal Engine Developer',
    year: '2023',
    yearRange: 'ott 2023 – set 2024',
    location: 'Da remoto',
    description: 'Sviluppo gameplay in Unreal Engine 5 in un team indie. Progettazione di sistemi in Blueprint, cinematics e ottimizzazione di ambienti 3D real-time su pipeline Git collaborativa.',
    logo: '/logos/lambdacorp.jpg',
  },
  {
    id: 'babalu',
    side: 'left',
    institution: 'BABALÙ APP',
    role: 'Operatore Video & Stand Fieristico',
    year: '2024',
    yearRange: 'dic 2023 – apr 2025',
    location: 'Milano · Torino · Roma',
    description: 'Freelance. Montaggio e post-produzione video, motion graphics e gestione tecnica di stand fieristici su scala nazionale. DaVinci Resolve, After Effects e attrezzatura di ripresa professionale.',
    logo: '/logos/babalu.jpg',
  },
  {
    id: 'leroy-merlin',
    side: 'right',
    institution: 'LEROY MERLIN',
    role: 'Addetto Supply Chain',
    year: '2024',
    yearRange: 'gen 2024 – lug 2024',
    location: 'Busnago (MB)',
    description: 'Part-time. Gestione del flusso merci interno, ricezione forniture e supporto alla supply chain del punto vendita in contesto retail di grande distribuzione.',
    logo: '/logos/leroy-merlin.jpg',
  },
  {
    id: 'digitech-tech',
    side: 'left',
    institution: 'DIGITECH CENTER S.R.L.',
    role: 'Responsabile Tecnico & Multimedia',
    year: '2024',
    yearRange: 'set 2024 – Presente',
    location: 'Vimercate (MB)',
    description: 'Gestione dell\'infrastruttura tecnica e produzione di contenuti multimediali aziendali: video, grafica, presentazioni e materiali digitali per corsi professionali e comunicazione.',
    logo: '/logos/digitech.jpg',
  },
  {
    id: 'digitech-form',
    side: 'right',
    institution: 'DIGITECH CENTER S.R.L.',
    role: 'Formatore Sicurezza sul Lavoro',
    year: '2024',
    yearRange: 'nov 2024 – Presente',
    location: 'Vimercate (MB)',
    description: 'Docente di corsi obbligatori sulla sicurezza nei luoghi di lavoro (D.Lgs. 81/08). Gestione in aula, predisposizione materiali didattici e documentazione dei partecipanti.',
    logo: '/logos/digitech.jpg',
  },
]

export const CERTIFICATIONS: Certification[] = [
  { id: 'google-it', title: 'Google IT Support Professional', issuer: 'Google / Coursera', year: '2023' },
  { id: 'blender', title: 'Blender Certified Artist', issuer: 'Blender Foundation', year: '2023' },
  { id: 'maya', title: 'Autodesk Certified User — Maya', issuer: 'Autodesk', year: '2023' },
  { id: 'threejs', title: 'Three.js Journey', issuer: 'Bruno Simon / Threejs', year: '2023' },
  { id: 'adobe', title: 'Adobe Certified — Premiere Pro', issuer: 'Adobe', year: '2023' },
  { id: 'comptia', title: 'CompTIA IT Fundamentals+', issuer: 'CompTIA', year: '2023' },
]

export const SOCIAL_LINKS: SocialLink[] = [
  { id: 'github', label: 'GitHub', url: 'https://github.com/shankar-mattavelli' },
  { id: 'linkedin', label: 'LinkedIn', url: 'https://linkedin.com/in/shankar-mattavelli' },
  { id: 'twitter', label: 'Twitter', url: 'https://twitter.com/shankar_mattavelli' },
]

export const NAV_ITEMS = [
  { label: 'PROGETTI', href: '#progetti' },
  { label: 'PERCORSO', href: '#percorso' },
  { label: 'CERTIFICAZIONI', href: '#certificazioni' },
  { label: 'CONTATTO', href: '#contatto' },
] as const
